### ISSUE TITLE
Wrong GRU-D update functions

### ISSUE THREAD

**Issue by Thartvigsen** [zhiyongc/GRU-D#2]
I think one update function is wrong.. on line 123 in GRUD.py your update equation is:
```
h_tilde = F.tanh(self.hl(combined))
h = (1 - z) * h + z * h_tilde
```
according to the paper, they should be
```
new_combined = torch.cat((x, torch.mul(r, h), m), dim=2)
h_tilde = F.tanh(self.hl(new_combined))
h = (1 - z)*h + z*h_tilde
```
When computing h_tilde in the GRU cell, you have to first multiply the hidden state with the reset gate.

**Comment by zhiyongc** [comment]
This issue is fixed in the code. Thanks

**Comment by Thartvigsen** [comment]
Thanks for sorting this out.
